### ISSUE TITLE
Erro normalização na nova versão

### ISSUE THREAD

**Issue by staticdev** [tfcbertaglia/enelvo#2]
Olá Thales,

Acabei de baixar o código atual do enelvo e começou a dar erro (estava funcionando normalmente). Veja abaixo:

![image](https://user-images.githubusercontent.com/1446633/35011975-3a16b24c-faef-11e7-8d49-2fd2cda211ea.png)

**Comment by tfcbertaglia** [comment]
Arrumei, é pra funcionar agora.
