### ISSUE TITLE
Error setup.py

### ISSUE THREAD

**Issue by ltkacser** [tfcbertaglia/enelvo#8]
Foi tudo instalado corretamente, porem quando roda o setup.py acontece esse erro:
$ python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-10765.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/
---------------------------

Tentei com sudo e deu o seguinte erro:

error: urllib3 1.25.2 is installed but urllib3<1.25,>=1.20; python_version >= "3.4" is required by {'botocore'}

**Comment by staticdev** [comment]
Vish.. tive esse erro recentemente tb. Parece que teve uma atualização do urlib que quebrou um tanto de pacote. Tenho que ver oq eu fiz pra arrumar...

**Comment by tfcbertaglia** [comment]
@ltkacser, a sugestão do @staticdev funcionou? Avisa que aí eu mudo os requirements. Valeu!

**Comment by ltkacser** [comment]
Eu utilizei urllib3==1.22 e funcionou. Estava com a urllib3==1.25 antes
Mas tem que rodar em sudo mesmo?

**Comment by staticdev** [comment]
@ltkacser testei com urllib3==1.24.1 e funcionou tb.

**Comment by tfcbertaglia** [comment]
Mudei a versão no requirements. 

@ltkacser não era pra obrigatoriamente precisar rodar em sudo, tenho que ver o que aconteceu. Essa semana vou commitar umas alterações aí eu verifico tudo isso.
